// Code generated by tygo. DO NOT EDIT.

//////////
// source: wire.go

export interface AccountStatus {
  connected: boolean;
  provider?: string;
  account?: string;
  connectedAt?: string;
}
export interface AuthorizationStart {
  handle: string;
  userCode: string;
  verificationUri: string;
  expiresInSeconds: number /* int64 */;
  intervalSeconds: number /* int64 */;
}
export interface AuthorizationPoll extends AccountStatus {
  status: string;
  intervalSeconds?: number /* int64 */;
}
export interface AuthorizationRequest {
  provider: string;
}
