// Code generated by tygo. DO NOT EDIT.

//////////
// source: wire.go

export interface ClientFrame {
  type: string;
  cols?: number /* uint16 */;
  rows?: number /* uint16 */;
}
export interface ServerFrame {
  type: string;
  code?: number /* int */;
  message?: string;
}
