// Code generated by tygo. DO NOT EDIT.

//////////
// source: wire.go

export interface OAuthConfigResponse {
  issuer: string;
  authorizationEndpoint: string;
  clientId: string;
  scope: string;
}
export interface ExchangeRequest {
  code: string;
  codeVerifier: string;
  redirectUri: string;
}
export interface DeviceResponse {
  deviceCode: string;
  userCode: string;
  verificationUriComplete: string;
  intervalSeconds: number /* int64 */;
}
export interface DevicePollRequest {
  deviceCode: string;
}
export interface DevicePoll extends Partial<TokenResponse> {
  status: string;
  intervalSeconds?: number /* int64 */;
}
export interface RefreshRequest {
  refreshToken: string;
}
export interface TokenResponse {
  idToken: string;
  refreshToken?: string;
  expiresInSeconds: number /* int64 */;
}
