// Code generated by tygo. DO NOT EDIT.

//////////
// source: wire.go

export interface Gres {
  name: string;
  count: number /* int */;
}
export interface Partition {
  name: string;
  cpuCount: number /* int */;
  memoryMb: number /* int */;
  gres: Gres[];
}
export interface Resource {
  host: string;
  accounts: string[];
  partitions: Partition[];
  homeDir: string;
}
export interface Resources {
  cores: number /* int */;
  memoryMb: number /* int */;
  wallMinutes: number /* int */;
  gpuType?: string;
  gpuCount?: number /* int */;
}
export interface CreateRequest {
  idempotencyKey?: string;
  sshHost: string;
  account?: string;
  partition: string;
  rootFolder: string;
  resources: Resources;
  tunnelModes?: string[];
}
export interface SessionResponse {
  id: string;
  seq: number /* int */;
  state: string;
  launcher: string;
  sshHost: string;
  account?: string;
  partition: string;
  rootFolder: string;
  resources: Resources;
  tunnelModes: string[];
  error?: string;
  createdAt: string;
  startedAt?: string;
  updatedAt: string;
}
export interface SessionList {
  sessions: SessionResponse[];
  logs: SessionLogTail[];
}
export interface LinkAccess {
  url: string;
  token: string;
}
export interface DevtunnelAccess {
  id: string;
  cluster: string;
  hostToken: string;
}
export interface AttachResponse {
  session: SessionResponse;
  link?: LinkAccess;
  devtunnel?: DevtunnelAccess;
}
export interface SessionAccessResponse {
  sessionId: string;
  seq: number /* int */;
  expiresAt: string;
  jupyter: SessionJupyterAccess;
}
export interface SessionJupyterAccess {
  uri: string;
  token: string;
}
export interface ValidationResult {
  sessionId: string;
  script: string;
  status: string;
  message: string;
  stdout?: string;
  stderr?: string;
}
export interface RunList {
  runs: Run[];
}
export interface FinishedRun {
  finalState: string;
  error?: string;
  startedAt?: string;
  endedAt: string;
  stats?: RunStats;
  samples?: MetricSample[];
}
export interface SessionHistory {
  createdAt?: string;
  runs: FinishedRun[];
}
export interface SSHAccessResponse {
  port: number /* int */;
}
export interface SessionLogLine {
  stream: string;
  text: string;
  at: string;
}
export interface SessionLogTail {
  sessionId: string;
  lines: SessionLogLine[];
}
export interface GPUSample {
  index: number /* int */;
  utilPct: number /* int */;
  memUsedMiB: number /* int */;
  memTotalMiB: number /* int */;
}
export interface MetricSample {
  at: string;
  memBytes?: number /* int64 */;
  cpuUsageUsec?: number /* int64 */;
  gpus?: GPUSample[];
}
export interface SessionSeries {
  sessionId: string;
  samples: MetricSample[];
}
export interface RunStats {
  cores?: number /* int */;
  requestedMemory?: string;
  elapsedSeconds?: number /* int64 */;
  maxRss?: string;
  cpuEfficiencyPct?: number /* float64 */;
  memoryEfficiencyPct?: number /* float64 */;
}
export interface Run {
  sessionId: string;
  seq: number /* int */;
  sshHost: string;
  account?: string;
  partition: string;
  rootFolder: string;
  resources: Resources;
  tunnelModes: string[];
  finalState: string;
  error?: string;
  startedAt?: string;
  endedAt: string;
  stats?: RunStats;
  samples?: MetricSample[];
  logs?: SessionLogLine[];
}
