// Code generated by tygo. DO NOT EDIT.

//////////
// source: wire.go

export interface HostEntry {
  alias: string;
  hostname?: string;
  user?: string;
  port?: number /* int */;
  keyId?: string;
  extraDirectives: string[];
  managed: boolean;
}
export interface HostList {
  hosts: HostEntry[];
}
export interface SSHKey {
  id: string;
  type: string;
  fingerprint: string;
}
export interface SSHKeyList {
  keys: SSHKey[];
}
export interface SSHKeyRequest {
  id: string;
  privateKey: string;
}
export interface AddHostRequest {
  alias: string;
  command: string;
  keyId: string;
}
export interface UpdateHostRequest {
  command: string;
  keyId: string;
}
export interface HostHealth {
  alias: string;
  ok: boolean;
  message: string;
}
