// Code generated by tygo. DO NOT EDIT.

//////////
// source: wire.go

export interface TunnelLinkStatus {
  linked: boolean;
  provider?: string;
  account?: string;
  linkedAt?: string;
}
export interface TunnelLinkStart {
  handle: string;
  userCode: string;
  verificationUri: string;
  expiresInSeconds: number /* int64 */;
  intervalSeconds: number /* int64 */;
}
export interface TunnelLinkPoll extends TunnelLinkStatus {
  status: string;
  intervalSeconds?: number /* int64 */;
}
export interface StartLinkRequest {
  provider: string;
}
